### ISSUE TITLE
Assertion failure in SeparateTermsDragListener.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer-two-variables#10]
Almost certainly related to https://github.com/phetsims/equality-explorer/issues/186 (TypeScript conversion).

I don't see this equality-explorer or equality-explorer-basics, so perhaps it's related to having 2 variables.

```
equality-explorer-two-variables : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663860758425/equality-explorer-two-variables/equality-explorer-two-variables_en.html?continuousTest=%7B%22test%22%3A%5B%22equality-explorer-two-variables%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1663860758425%22%2C%22timestamp%22%3A1663873164731%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663860758425/assert/js/assert.js:28:13)
at assert (SeparateTermsDragListener.ts:215:24)
at animationCompletedCallback (EqualityExplorerMovable.ts:183:48)
at step (TermCreator.js:266:26)
at step (EqualityExplorerScene.ts:210:61)
at Array.forEach
at forEach (EqualityExplorerScene.ts:210:25)
at step (EqualityExplorerModel.ts:55:29)
at step (Sim.ts:432:21)
at apply (PhetioAction.ts:124:16)
id: Bayes Puppeteer
Snapshot from 9/22/2022, 9:32:38 AM
```

**Comment by pixelzoom** [comment]
Fixed in the above commit. CT is happy.  Closing.
