### ISSUE TITLE
CT: should not be called if disposed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer-two-variables#8]
Related to the assertion that was added to TinyEmitter in phetsims/axon#242.

All but one of these are "should not be called if disposed".  That one is "isInteger requires its argument to be a number: null" and may be symptomatic to the former.

```
equality-explorer-two-variables : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559712435679:50:17)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559712435679:247:27)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559712435679:160:14)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559712435679:316:34)
    at SeparateTermsDragListener.refreshHalos (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/TermDragListener.js?bust=1559712435679:371:45)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559712435679:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Emitter.js?bust=1559712435679:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Action.js?bust=1559712435679:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Emitter.js?bust=1559712435679:71:21)
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

equality-explorer-two-variables : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: isInteger requires its argument to be a number: null
Error: Assertion failed: isInteger requires its argument to be a number: null
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at Object.isInteger (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/dot/js/Util.js?bust=1559712435679:576:17)
    at Grid.isValidCell (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Grid.js?bust=1559712435679:413:21)
    at Grid.getClosestEquivalentTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Grid.js?bust=1559712435679:236:30)
    at Plate.getClosestEquivalentTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Plate.js?bust=1559712435679:221:24)
    at SeparateTermsDragListener.startOpposite (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/SeparateTermsDragListener.js?bust=1559712435679:87:48)
    at SeparateTermsDragListener.start (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/TermDragListener.js?bust=1559712435679:155:26)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559712435679:119:28
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Action.js?bust=1559712435679:177:20)
    at SeparateTermsDragListener.startDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559712435679:319:28)
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

equality-explorer-two-variables : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559712435679:50:17)
    at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559712435679:247:27)
    at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559712435679:160:14)
    at VariableTerm.moveTo (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/EqualityExplorerMovable.js?bust=1559712435679:118:29)
    at SeparateTermsDragListener.drag (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/TermDragListener.js?bust=1559712435679:201:17)
    at SimpleDragHandler.dragAction.Action.phetioHighFrequency (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559712435679:173:27)
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Action.js?bust=1559712435679:177:20)
    at Object.move (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559712435679:300:25)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/Input.js?bust=1559712435679:1750:27)
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

equality-explorer-two-variables : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559736450810:50:17)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559736450810:247:27)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559736450810:160:14)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559736450810:316:34)
    at SeparateTermsDragListener.refreshHalos (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/TermDragListener.js?bust=1559736450810:371:45)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559736450810:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Emitter.js?bust=1559736450810:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Action.js?bust=1559736450810:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Emitter.js?bust=1559736450810:71:21)
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

equality-explorer-two-variables : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: isInteger requires its argument to be a number: null
Error: Assertion failed: isInteger requires its argument to be a number: null
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at Object.isInteger (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/dot/js/Util.js?bust=1559736450810:576:17)
    at Grid.isValidCell (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Grid.js?bust=1559736450810:413:21)
    at Grid.getClosestEquivalentTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Grid.js?bust=1559736450810:236:30)
    at Plate.getClosestEquivalentTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Plate.js?bust=1559736450810:221:24)
    at SeparateTermsDragListener.startOpposite (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/SeparateTermsDragListener.js?bust=1559736450810:87:48)
    at SeparateTermsDragListener.start (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/TermDragListener.js?bust=1559736450810:155:26)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559736450810:119:28
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Action.js?bust=1559736450810:177:20)
    at SeparateTermsDragListener.startDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559736450810:319:28)
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

equality-explorer-two-variables : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559715146776:50:17)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559715146776:247:27)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559715146776:160:14)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559715146776:316:34)
    at SeparateTermsDragListener.refreshHalos (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/TermDragListener.js?bust=1559715146776:371:45)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559715146776:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Emitter.js?bust=1559715146776:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Action.js?bust=1559715146776:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Emitter.js?bust=1559715146776:71:21)
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

equality-explorer-two-variables : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: term not found: ConstantTerm: -1/1
Error: Assertion failed: term not found: ConstantTerm: -1/1
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at Grid.removeTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Grid.js?bust=1559715146776:280:17)
    at Plate.removeTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Plate.js?bust=1559715146776:129:28)
    at ConstantTermCreator.removeTermFromPlate (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/TermCreator.js?bust=1559715146776:401:29)
    at SeparateTermsDragListener.start (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/TermDragListener.js?bust=1559715146776:159:28)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559715146776:119:28
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Action.js?bust=1559715146776:177:20)
    at SeparateTermsDragListener.startDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559715146776:319:28)
    at SeparateTermsDragListener.tryToSnag (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559715146776:372:14)
    at SeparateTermsDragListener.tryTouchToSnag (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559715146776:379:14)
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

equality-explorer-two-variables : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559738854067:50:17)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559738854067:247:27)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559738854067:160:14)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559738854067:316:34)
    at SeparateTermsDragListener.refreshHalos (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/TermDragListener.js?bust=1559738854067:371:45)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559738854067:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Emitter.js?bust=1559738854067:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Action.js?bust=1559738854067:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Emitter.js?bust=1559738854067:71:21)
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

equality-explorer-two-variables : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559718787019:50:17)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559718787019:247:27)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559718787019:160:14)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559718787019:316:34)
    at SeparateTermsDragListener.refreshHalos (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/TermDragListener.js?bust=1559718787019:371:45)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559718787019:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Emitter.js?bust=1559718787019:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Action.js?bust=1559718787019:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Emitter.js?bust=1559718787019:71:21)
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

equality-explorer-two-variables : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: isInteger requires its argument to be a number: null
Error: Assertion failed: isInteger requires its argument to be a number: null
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at Object.isInteger (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/dot/js/Util.js?bust=1559718787019:576:17)
    at Grid.isValidCell (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Grid.js?bust=1559718787019:413:21)
    at Grid.getClosestEquivalentTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Grid.js?bust=1559718787019:236:30)
    at Plate.getClosestEquivalentTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Plate.js?bust=1559718787019:221:24)
    at SeparateTermsDragListener.startOpposite (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/SeparateTermsDragListener.js?bust=1559718787019:87:48)
    at SeparateTermsDragListener.start (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/TermDragListener.js?bust=1559718787019:155:26)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559718787019:119:28
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Action.js?bust=1559718787019:177:20)
    at SeparateTermsDragListener.startDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559718787019:319:28)
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

equality-explorer-two-variables : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559718787019:50:17)
    at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559718787019:247:27)
    at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559718787019:160:14)
    at VariableTerm.moveTo (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/EqualityExplorerMovable.js?bust=1559718787019:118:29)
    at SeparateTermsDragListener.drag (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/TermDragListener.js?bust=1559718787019:201:17)
    at SimpleDragHandler.dragAction.Action.phetioHighFrequency (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559718787019:173:27)
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Action.js?bust=1559718787019:177:20)
    at Object.move (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559718787019:300:25)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/Input.js?bust=1559718787019:1750:27)
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

equality-explorer-two-variables : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559730245233:50:17)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559730245233:247:27)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559730245233:160:14)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Property.js?bust=1559730245233:316:34)
    at SeparateTermsDragListener.refreshHalos (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/TermDragListener.js?bust=1559730245233:371:45)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/TinyEmitter.js?bust=1559730245233:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Emitter.js?bust=1559730245233:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Action.js?bust=1559730245233:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Emitter.js?bust=1559730245233:71:21)
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM

equality-explorer-two-variables : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: isInteger requires its argument to be a number: null
Error: Assertion failed: isInteger requires its argument to be a number: null
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/assert/js/assert.js:22:13)
    at Object.isInteger (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/dot/js/Util.js?bust=1559730245233:576:17)
    at Grid.isValidCell (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Grid.js?bust=1559730245233:413:21)
    at Grid.getClosestEquivalentTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Grid.js?bust=1559730245233:236:30)
    at Plate.getClosestEquivalentTerm (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/model/Plate.js?bust=1559730245233:221:24)
    at SeparateTermsDragListener.startOpposite (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/SeparateTermsDragListener.js?bust=1559730245233:87:48)
    at SeparateTermsDragListener.start (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/equality-explorer/js/common/view/TermDragListener.js?bust=1559730245233:155:26)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559730245233:119:28
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/axon/js/Action.js?bust=1559730245233:177:20)
    at SeparateTermsDragListener.startDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1559708481094/scenery/js/input/SimpleDragHandler.js?bust=1559730245233:319:28)
id: Bayes Chrome
Approximately 6/4/2019, 10:21:21 PM
```

**Comment by pixelzoom** [comment]
Fixed in the above commit.  I'll give CT a couple of cycles to register its approval before closing.

**Comment by pixelzoom** [comment]
CT is happy after 4 cycles. Closing.

**Comment by pixelzoom** [comment]
Reopening, reappearing in CT on 6/6/19.

**Comment by pixelzoom** [comment]
This should be fixed in the above commit.  In TermDragListener `refreshHalos`, now checking whether any term has been disposed before setting its Property values.

I'll leave this open for a few CT cycles to confirm.

**Comment by pixelzoom** [comment]
This is like playing whack a mole.   Another case identified by CT addressed in above commit. 

```
equality-explorer-two-variables : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1560647804708/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1560647804708/axon/js/TinyEmitter.js?bust=1560655272793:50:17)
    at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1560647804708/axon/js/Property.js?bust=1560655272793:247:27)
    at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1560647804708/axon/js/Property.js?bust=1560655272793:160:14)
    at ConstantTerm.moveTo (https://bayes.colorado.edu/continuous-testing/snapshot-1560647804708/equality-explorer/js/common/model/EqualityExplorerMovable.js?bust=1560655272793:118:29)
    at locationListener (https://bayes.colorado.edu/continuous-testing/snapshot-1560647804708/equality-explorer/js/common/view/TermDragListener.js?bust=1560655272793:102:29)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1560647804708/axon/js/TinyEmitter.js?bust=1560655272793:59:55)
    at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1560647804708/axon/js/Property.js?bust=1560655272793:247:27)
    at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1560647804708/axon/js/Property.js?bust=1560655272793:160:14)
    at ConstantTerm.step (https://bayes.colorado.edu/continuous-testing/snapshot-1560647804708/equality-explorer/js/common/model/EqualityExplorerMovable.js?bust=1560655272793:173:33)
id: Bayes Chrome
Approximately 6/15/2019, 7:16:44 PM
```

**Comment by pixelzoom** [comment]
And another one, fixed in the above commit:

```
equality-explorer-two-variables : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be called if disposed
Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1560657600558/assert/js/assert.js:22:13)
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1560657600558/axon/js/TinyEmitter.js?bust=1560695474606:50:17)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1560657600558/axon/js/Property.js?bust=1560695474606:247:27)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1560657600558/axon/js/Property.js?bust=1560695474606:160:14)
    at BooleanProperty.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1560657600558/axon/js/Property.js?bust=1560695474606:316:34)
    at SeparateTermsDragListener.start (https://bayes.colorado.edu/continuous-testing/snapshot-1560657600558/equality-explorer/js/common/view/TermDragListener.js?bust=1560695474606:181:59)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1560657600558/scenery/js/input/SimpleDragHandler.js?bust=1560695474606:119:28
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1560657600558/axon/js/Action.js?bust=1560695474606:177:20)
    at SeparateTermsDragListener.startDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1560657600558/scenery/js/input/SimpleDragHandler.js?bust=1560695474606:319:28)
    at SeparateTermsDragListener.tryToSnag (https://bayes.colorado.edu/continuous-testing/snapshot-1560657600558/scenery/js/input/SimpleDragHandler.js?bust=1560695474606:372:14)
id: Bayes Chrome
Approximately 6/15/2019, 10:00:00 PM
```

**Comment by pixelzoom** [comment]
CT is still happy after 9 cycles, so I'm going to close this.
