### ISSUE TITLE
CT perennial task failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/equality-explorer-two-variables#9]
```
equality-explorer-two-variables : build : phet
Failure to grunt snapshot-1581958785866/equality-explorer-two-variables:
Running "lint-all" task
Fatal error: Perennial task failed:
Error: ENOSPC: no space left on device, open '/data/share/phet/continuous-testing/snapshot-1581958785866/chipper/eslint/cache/41a8310e437ce4f9a0ab15ecd3a39e34.eslintcache'
  at Object.openSync (fs.js:443:3)
  at Object.writeFileSync (fs.js:1194:35)
  at Function.writeFile.sync (/data/share/phet/continuous-testing/snapshot-1581958785866/chipper/node_modules/write/index.js:125:6)
  at writeJSON (/data/share/phet/continuous-testing/snapshot-1581958785866/chipper/node_modules/flat-cache/utils.js:37:11)
  at Object.save (/data/share/phet/continuous-testing/snapshot-1581958785866/chipper/node_modules/flat-cache/cache.js:119:5)
  at Object.reconcile (/data/share/phet/continuous-testing/snapshot-1581958785866/chipper/node_modules/file-entry-cache/cache.js:282:15)
  at LintResultCache.reconcile (/data/share/phet/continuous-testing/snapshot-1581958785866/chipper/node_modules/eslint/lib/cli-engine/lint-result-cache.js:138:29)
  at CLIEngine.executeOnFiles (/data/share/phet/continuous-testing/snapshot-1581958785866/chipper/node_modules/eslint/lib/cli-engine/cli-engine.js:825:29)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1581958785866/chipper/js/grunt/lint.js:91:22)
  at grunt.registerTask.wrapTask (/data/share/phet/continuous-testing/snapshot-1581958785866/chipper/js/grunt/Gruntfile.js:228:5)
  at Object.<anonymous> (/data/share/phet/continuous-testing/snapshot-1581958785866/chipper/js/grunt/Gruntfile.js:93:13)
  at Object.thisTask.fn (/data/share/phet/continuous-testing/snapshot-1581958785866/equality-explorer-two-variables/node_modules/grunt/lib/grunt/task.js:70:16)
  at Object.<anonymous> (/data/share/phet/continuous-testing/snapshot-1581958785866/equality-explorer-two-variables/node_modules/grunt/lib/util/task.js:294:30)
  at Task.runTaskFn (/data/share/phet/continuous-testing/snapshot-1581958785866/equality-explorer-two-variables/node_modules/grunt/lib/util/task.js:244:24)
  at Task.<anonymous> (/data/share/phet/continuous-testing/snapshot-1581958785866/equality-explorer-two-variables/node_modules/grunt/lib/util/task.js:293:12)
  at /data/share/phet/continuous-testing/snapshot-1581958785866/equality-explorer-two-variables/node_modules/grunt/lib/util/task.js:220:11
  at process._tickCallback (internal/process/next_tick.js:61:11)
  at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
  at startup (internal/bootstrap/node.js:283:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Full Error details:
{
  "errno": -28,
  "syscall": "open",
  "code": "ENOSPC",
  "path": "/data/share/phet/continuous-testing/snapshot-1581958785866/chipper/eslint/cache/41a8310e437ce4f9a0ab15ecd3a39e34.eslintcache"
}


Approximately 2/17/2020, 9:59:45 AM
```

**Comment by pixelzoom** [comment]
This means that the server has run out of disk space, and is affecting multiple sims in CT.   It looks like this is being discussed/investigated in dev-public Slack channel, so I'm just going to close this issue, since there is nothing sim-specific to be done.
